apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: music-catalog
data:
  APP_BASE_URL: "https://music-catalog.local:8443"
  KEYCLOAK_EXTERNAL_URL: "https://music-catalog.local:8443/auth"
