apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"TraceId":"(\w+)"'
          name: TraceID
          url: "$${__value.raw}"
          
  - name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      lokiSearch:
        datasourceUid: Loki
      nodeGraph:
        enabled: true