global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'music-catalog'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'api-gateway:8080'
        - 'artist-service:8080'
        - 'catalog-service:8080'
        - 'orchestrator-service:8080'
        - 'scraper-service:8080'
        - 'notification-service:8080'