apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artists-db
  namespace: music-catalog
spec:
  serviceName: artists-db
  replicas: 1
  selector:
    matchLabels:
      app: artists-db
  template:
    metadata:
      labels:
        app: artists-db
    spec:
      containers:
        - name: artists-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: artists-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: artists-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: artists-secret
                  key: database
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "50Mi"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(ARTISTS_DB_USER)
                - -d
                - $(ARTISTS_DB)
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(ARTISTS_DB_USER)
                - -d
                - $(ARTISTS_DB)
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: artists-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: artists-storage
          persistentVolumeClaim:
            claimName: artists-data