apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artists-db
  namespace: music-catalog
spec:
  serviceName: artists-db
  replicas: 1
  selector:
    matchLabels:
      app: artists-db
  template:
    metadata:
      labels:
        app: artists-db
    spec:
      # fix this
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-data