apiVersion: apps/v1
kind: Deployment
metadata:
  name: artists-service
  namespace: music-catalog
  labels:
    app: artists-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artists-service
  template:
    metadata:
      labels:
        app: artists-service
    spec:
      containers:
        - name: artists-service
          image: wisnieibiszkopty/music-catalog-artist-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: artists-service-secret
                  key: connection-string
            - name: ConnectionStrings__RabbitMq
              valueFrom:
                secretKeyRef:
                  name: artists-service-secret
                  key: rabbitmq-url
            - name: Keycloak__InternalUrl
              valueFrom:
                configMapKeyRef:
                  name: artists-service-config
                  key: Keycloak__InternalUrl
            - name: Keycloak__Realm
              valueFrom:
                configMapKeyRef:
                  name: artists-service-config
                  key: Keycloak__Realm
            - name: Otlp__Endpoint
              valueFrom:
                configMapKeyRef:
                  name: artists-service-config
                  key: Otlp__Endpoint
            - name: NPGSQL_GSSAPI_LIBRARIES
              valueFrom:
                configMapKeyRef:
                  name: artists-service-config
                  key: NPGSQL_GSSAPI_LIBRARIES
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
      restartPolicy: Always