apiVersion: v1
kind: Secret
metadata:
  name: artist-service-secret
  namespace: music-catalog
type: Opaque
stringData:
  connection-string: "Host=artist-db;Port=5432;Database=artist-db;Username=developer;Password=password"
  url: "jdbc:postgresql://artist-db:5432/artist-db"
  user: "developer"
  password: "password"
  rabbitmq-url: "amqp://user:password@rabbitmq:5672"