apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: music-catalog
type: Opaque
stringData:
  connection-string: "Host=catalog-db;Port=5432;Database=catalog-db;Username=developer;Password=password"
  url: "jdbc:postgresql://catalog-db:5432/catalog-db"
  user: "developer"
  password: "password"
  rabbitmq-url: "amqp://user:password@rabbitmq:5672"