apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: music-catalog
  labels:
    app: notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: notification-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: notification-service
          image: wisnieibiszkopty/music-catalog-notification-service:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          envFrom:
            - configMapRef:
                name: shared-config
          env:
            - name: ConnectionStrings__RabbitMq
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: rabbitmq-url
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
