services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    expose:
      - "5672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

  redis:
    image: redis:8.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  api-gateway:
    container_name: api-gateway
    build:
      context: ..
      dockerfile: src/gateway/ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - keycloak
      - artist-service
      - orchestrator-service  
  
  web-app:
    container_name: web-app
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080/api
        - VITE_KEYCLOAK_URL=http://localhost:8080/auth
  
  keycloak-db:
    image: postgres:18-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start --import-realm
    environment:
      KC_HOSTNAME_URL: http://localhost:8080/auth
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080/auth
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: /auth
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    restart: unless-stopped
    depends_on:
      - keycloak-db

  orchestrator-service:
    container_name: orchestrator-service
    build:
      context: ..
      dockerfile: src/services/Orchestrator.Service/Dockerfile
    environment:
      ConnectionStrings__RabbitMq: rabbitmq://guest:guest@rabbitmq
      ConnectionStrings__Redis: redis:6379
      Redis__InstanceName: ScrapperService
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - rabbitmq
      - redis
    
  scraper-service:
    container_name: scraper-service
    build:
      context: ..
      dockerfile: src/services/Scraper.Service/Dockerfile
    environment:
      ConnectionStrings__RabbitMq: rabbitmq://guest:guest@rabbitmq
      ConnectionStrings__Redis: redis:6379,abortConnect=false
      ASPNETCORE_URLS: http://+:8080
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - rabbitmq
      - redis

  notification-service:
    container_name: notification-service
    build: 
      context: ..
      dockerfile: src/services/Notification.Service/Dockerfile
    environment:
      ConnectionStrings__RabbitMq: rabbitmq://guest:guest@rabbitmq
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - rabbitmq

  artist-db:
    image: postgres:18-alpine
    container_name: artist-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=artist_db
    volumes:
      - artist-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d artist-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  artist-db-migrator:
    image: flyway/flyway:latest-alpine
    container_name: artist-db-migrator
    volumes:
      - ../src/services/Artists.Service/migrations:/flyway/sql
    depends_on:
      artist-db:
        condition: service_healthy
    command: -url=jdbc:postgresql://artist-db:5432/artist_db -user=admin -password=123 -connectRetries=60 migrate

  artist-service:
    container_name: artist-service
    build:
      context: ..
      dockerfile: src/services/Artists.Service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=artist-db;Port=5432;Database=artist_db;Username=admin;Password=123
      ConnectionStrings__RabbitMq: rabbitmq://guest:guest@rabbitmq
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      artist-db:
        condition: service_healthy
  
  catalog-db:
    image: postgres:18-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=catalog_db
    volumes:
      - catalog-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d catalog-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog-db-migrator:
    image: flyway/flyway:latest-alpine
    container_name: catalog-db-migrator
    volumes:
      - ../src/services/Catalog.Service/migrations:/flyway/sql
    depends_on:
      artist-db:
        condition: service_healthy
    command: -url=jdbc:postgresql://artist-db:5432/catalog_db -user=admin -password=123 -connectRetries=60 migrate

  catalog-service:
    container_name: catalog-service
    build:
      context: ..
      dockerfile: src/services/Catalog.Service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=artist-db;Port=5432;Database=artist_db;Username=admin;Password=123
      ConnectionStrings__RabbitMq: rabbitmq://guest:guest@rabbitmq
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      catalog-db:
        condition: service_healthy
  
volumes:
  keycloak-data:
  artist-data:
  catalog-data:
  redis-data:
  rabbitmq-data:
  rabbitmq-log: