services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    expose:
      - "5672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

  redis:
    image: redis:8.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  api-gateway:
    container_name: api-gateway
    build:
      context: ..
      dockerfile: services/ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      Keycloak__InternalUrl: ${KEYCLOAK_INTERNAL_URL}
      Keycloak__ExternalUrl: ${KEYCLOAK_EXTERNAL_URL}
      Keycloak__Realm: ${KEYCLOAK_REALM}
      Keycloak__Audience: ${KEYCLOAK_AUDIENCE}
      AllowedOrigins__0: ${GATEWAY_URL}
      AllowedOrigins__1: ${GATEWAY_URL_2}
    networks:
      - default
    depends_on:
      - keycloak
      - artist-service
      - orchestrator-service  

  # frontend      
  web-app:
    container_name: web-app
    build:
      context: ..
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${GATEWAY_URL}
  
  # identity provider
  keycloak-db:
    image: postgres:18-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloakkye
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start --import-realm
    environment:
      KC_HOSTNAME_URL: ${KEYCLOAK_EXTERNAL_URL}
      KC_HOSTNAME_ADMIN_URL: ${KEYCLOAK_EXTERNAL_URL}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: /auth
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    restart: unless-stopped
    depends_on:
      - keycloak-db

  # scraping
  orchestrator-service:
    container_name: orchestrator-service
    build:
      context: ..
      dockerfile: services/Orchestrator.Service/Dockerfile
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__RabbitMq: ${RABBIT_URL}
      ConnectionStrings__Redis: ${REDIS_URL}
      Redis__InstanceName: ScrapperService
      Keycloak__InternalUrl: ${KEYCLOAK_INTERNAL_URL}
      Keycloak__Realm: ${KEYCLOAK_REALM}
    depends_on:
      - rabbitmq
      - redis
    
  scraper-service:
    container_name: scraper-service
    build:
      context: ..
      dockerfile: services/Scraper.Service/Dockerfile
    env_file:
      - .env
      - .env.secrets
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__RabbitMq: ${RABBIT_URL}
      ConnectionStrings__Redis: ${REDIS_URL},abortConnect=false
    depends_on:
      - rabbitmq
      - redis

  # notifications
  notification-service:
    container_name: notification-service
    build:
      context: ..
      dockerfile: services/Notification.Service/Dockerfile
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__RabbitMq: ${RABBIT_URL}
      Keycloak__InternalUrl: ${KEYCLOAK_INTERNAL_URL}
      Keycloak__Realm: ${KEYCLOAK_REALM}
    depends_on:
      - rabbitmq

  # artists
  artist-db:
    image: postgres:18-alpine
    container_name: artist-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=artist_db
    volumes:
      - artist-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d artist_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  artist-db-migrator:
    image: flyway/flyway:latest-alpine
    container_name: artist-db-migrator
    volumes:
      - ../services/Artists.Service/migrations:/flyway/sql
    depends_on:
      artist-db:
        condition: service_healthy
    command: -url=jdbc:postgresql://artist-db:5432/artist_db -user=admin -password=123 -connectRetries=60 migrate

  artist-service:
    container_name: artist-service
    build:
      context: ..
      dockerfile: services/Artists.Service/Dockerfile
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DefaultConnection: Host=artist-db;Port=5432;Database=artist_db;Username=admin;Password=123
      ConnectionStrings__RabbitMq: ${RABBIT_URL}
      Keycloak__InternalUrl: ${KEYCLOAK_INTERNAL_URL}
      Keycloak__Realm: ${KEYCLOAK_REALM}
    depends_on:
      artist-db:
        condition: service_healthy
  
  # catalog
  catalog-db:
    image: postgres:18-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=catalog_db
    volumes:
      - catalog-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d catalog_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog-db-migrator:
    image: flyway/flyway:latest-alpine
    container_name: catalog-db-migrator
    volumes:
      - ../services/Catalog.Service/migrations:/flyway/sql
    depends_on:
      artist-db:
        condition: service_healthy
    command: -url=jdbc:postgresql://catalog-db:5432/catalog_db -user=admin -password=123 -connectRetries=60 migrate

  catalog-service:
    container_name: catalog-service
    build:
      context: ..
      dockerfile: services/Catalog.Service/Dockerfile
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DefaultConnection: Host=catalog-db;Port=5432;Database=catalog_db;Username=admin;Password=123
      ConnectionStrings__RabbitMq: ${RABBIT_URL}
      Keycloak__InternalUrl: ${KEYCLOAK_INTERNAL_URL}
      Keycloak__Realm: ${KEYCLOAK_REALM}
    depends_on:
      catalog-db:
        condition: service_healthy
  
  # observability
  loki:
    container_name: loki
    image: grafana/loki:3.7
    expose:
      - "3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - logging
    command: -config.file=/etc/loki/local-config.yaml
  
  promtail:
    container_name: promtail
    image: grafana/promtail:3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml
    networks:
      - logging
    command: -config.file=/etc/promtail/config.yaml
  
  grafana:
    container_name: grafana
    image: grafana/grafana:12.3.6
    volumes:
      - ./config/grafana-ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=lax
      - GF_SERVER_ENABLE_GZIP=true
    networks:
      - logging
      - default
  
networks:
  default:
  logging:
    driver: bridge
    internal: false
  
volumes:
  keycloak-data:
  artist-data:
  catalog-data:
  redis-data:
  rabbitmq-data:
  rabbitmq-log:
  loki-data:
  grafana-data: