@hostname = localhost
@port = 8080
@gatewayUrl = http://{{hostname}}:{{port}}
@realm = music-catalog

### 

GET {{gatewayUrl}}/auth/realms/{{realm}}/.well-known/openid-configuration

###

POST {{gatewayUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=api-client&
username=user&
password=user&
grant_type=password

> {%
    client.global.set("userToken", response.body.access_token);
%}

###

POST {{gatewayUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=api-client&
username=admin&
password=admin&
grant_type=password

> {%
client.global.set("adminToken", response.body.access_token);
%}

###

POST {{gatewayUrl}}/auth/admin/realms/{{realm}}/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "newuser",
  "enabled": true,
  "email": "new@user.com",
  "firstName": "Jan",
  "lastName": "Kowalski",
  "credentials": [
    {
      "type": "password",
      "value": "password123",
      "temporary": false
    }
  ]
}
###

GET http://localhost:8080/api/artists

###

GET http://localhost:8080/api/artists/550e8400-e29b-41d4-a716-446655440000

###

DELETE http://localhost:8080/api/artists/550e8400-e29b-41d4-a716-446655440000
Authorization: Bearer {{userToken}}

###

GET http://localhost:8080/api/artists
Authorization: Bearer {{adminToken}}
