@hostname = localhost
@port = 8080
@gatewayUrl = http://{{hostname}}:{{port}}
@realm = music-catalog

### 

GET {{gatewayUrl}}/auth/realms/{{realm}}/.well-known/openid-configuration

###

POST {{gatewayUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=api-client&
username=user&
password=user&
grant_type=password

> {%
    client.global.set("userToken", response.body.access_token);
%}

###

POST {{gatewayUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=api-client&
username=admin&
password=admin&
grant_type=password

> {%
client.global.set("adminToken", response.body.access_token);
%}

###

POST {{gatewayUrl}}/auth/admin/realms/{{realm}}/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "newuser",
  "enabled": true,
  "email": "new@user.com",
  "firstName": "Jan",
  "lastName": "Kowalski",
  "credentials": [
    {
      "type": "password",
      "value": "password123",
      "temporary": false
    }
  ]
}
###

GET http://localhost:8080/api/artists

###

GET http://localhost:8080/api/artists/05bh1HQ397HsnksmwQgdEi

###

POST http://localhost:8080/api/artists
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "Radiohead",
  "isBand": true
}

###

PUT http://localhost:8080/api/artists
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "id": "05bh1HQ397HsnksmwQgdEi",
  "name": "Radiohead",
  "foundedYear": 1985,
  "isBand": true
}

###

DELETE http://localhost:8080/api/artists/7dGJo4pcD2V6oG8kP0tJRR
Authorization: Bearer {{adminToken}}

###

POST http://localhost:8080/api/scraper/artists/eminem
Authorization: Bearer {{adminToken}}

### Get Eminem Albums

POST http://localhost:8080/api/scraper/albums/7dGJo4pcD2V6oG8kP0tJRR
Authorization: Bearer {{adminToken}}

### Get Wisp Albums

POST http://localhost:8080/api/scraper/albums/3TJZG17pjOKXwx1ELKJPfm
Authorization: Bearer {{adminToken}}

###

GET http://localhost:8080/api/catalog/albums/7dGJo4pcD2V6oG8kP0tJRR

###


GET http://localhost:8080/api/catalog/albums/songs/2cWBwpqMsDJC1ZUwz813lo

###

DELETE http://localhost:8080/api/catalog/2cWBwpqMsDJC1ZUwz813lo
Authorization: Bearer {{adminToken}}