apiVersion: v1
kind: Secret
metadata:
  name: scraper-service-secret
  namespace: music-catalog
type: Opaque
stringData:
  rabbitmq-url: "amqp://user:password@rabbitmq:5672"
  redis-url: "redis:6379,password=password,abortConnect=false"
  spotify-client-id: ""
  spotify-client-secret: ""
