@Scraper.Service_HostAddress = http://localhost:5288

###

@clientId=
@clientSecret=

POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{clientId}}&client_secret={{clientSecret}}

###

@bearer=

GET https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb
Authorization: Bearer {{bearer}}


###

GET https://api.spotify.com/v1/search?q=radiohead&type=artist&limit=1
Authorization: Bearer {{bearer}}