apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: music-catalog
  labels:
    app.kubernetes.io/monitored-by: prometheus
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  