FROM mcr.microsoft.com/dotnet/aspnet:10.0-noble-chiseled AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
ARG TARGETARCH

WORKDIR /src

COPY ["services/ApiGateway/ApiGateway.csproj", "services/ApiGateway/"]
COPY ["shared/Shared/Shared.csproj", "shared/Shared/"]
COPY ["shared/Contracts/Contracts.csproj", "shared/Contracts/"]

RUN --mount=type=cache,id=nuget-ApiGateway-$TARGETARCH,target=/root/.nuget/packages \
    dotnet restore "services/ApiGateway/ApiGateway.csproj" -a $TARGETARCH

COPY services/ApiGateway/ services/ApiGateway/
COPY shared/ shared/

WORKDIR "/src/services/ApiGateway"
RUN --mount=type=cache,id=nuget-ApiGateway-$TARGETARCH,target=/root/.nuget/packages \
    dotnet build ./ -c $BUILD_CONFIGURATION -o /app/build --no-restore -a $TARGETARCH

FROM build AS publish
ARG TARGETARCH
ARG BUILD_CONFIGURATION=Release
RUN --mount=type=cache,id=nuget-ApiGateway-$TARGETARCH,target=/root/.nuget/packages \
    dotnet publish "ApiGateway.csproj" -c $BUILD_CONFIGURATION -a $TARGETARCH -o /app/publish /p:UseAppHost=false --no-restore

FROM base AS final
WORKDIR /app

LABEL \
    org.opencontainers.image.title="api-gateway" \
    org.opencontainers.image.version="0.1.0" \
    org.opencontainers.image.description="Api Gateway" \
    org.opencontainers.image.source="https://github.com/wisnieibiszkopty/music-catalog"

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApiGateway.dll"]