@hostname = localhost
@port = 8080
@gatewayUrl = http://{{hostname}}:{{port}}
@realm = music-catalog

### 

GET {{gatewayUrl}}/auth/realms/{{realm}}/.well-known/openid-configuration

### 

POST {{gatewayUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=api-client&
username=admin&
password=admin&
grant_type=password

### 

@adminToken = {{login.response.body.access_token}}

###

POST {{gatewayUrl}}/auth/admin/realms/{{realm}}/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "newuser",
  "enabled": true,
  "email": "new@user.com",
  "firstName": "Jan",
  "lastName": "Kowalski",
  "credentials": [
    {
      "type": "password",
      "value": "password123",
      "temporary": false
    }
  ]
}
###

GET {{gatewayUrl}}/api/artists

###

GET {{gatewayUrl}}/api/artists
Authorization: Bearer {{adminToken}}
