repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: groundhog2k
    url: https://groundhog2k.github.io/helm-charts/
    
releases:
  - name: redis
    namespace: music-catalog
    chart: bitnami/redis
    version: 25.5.3
    values:
      - auth:
          password: "password"
        master:
          persistence:
            size: 1Gi
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
        replica:
          replicaCount: 0
          
          
  - name: rabbitmq
    namespace: music-catalog
    chart: groundhog2k/rabbitmq
    version: 2.3.0
    values:
      - authentication:
          user:
            value: "user"
          password:
            value: "password"
          erlangCookie:
            value: "secreterlangcookie"
        env:
          - name: RABBITMQ_LOGS
            value: "-"
        storage:
          requestedSize: 1Gi
        resources:
          limits:
            cpu: 500m
            memory: 256Mi