# WYMAGANIE po stronie aplikacji:
# Każdy Service który chcesz monitorować musi mieć label:
#   app.kubernetes.io/monitored-by: prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-services-monitor
  namespace: music-catalog
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/monitored-by: prometheus
  
  namespaceSelector:
    matchNames:
      - music-catalog
  
  endpoints:
    - port: metrics  
      path: /metrics 
      interval: 30s  
      scrapeTimeout: 10s
