apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: music-catalog
  labels:
    app.kubernetes.io/monitored-by: prometheus
spec:
  selector:
    app: keycloak-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None