deploymentMode: SingleBinary

loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  limits_config:
    retention_period: 168h
    max_line_size: 256KB
  compactor:
    retention_enabled: true
    delete_request_store: filesystem

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: true
    storageClass: local-path
    size: 5Gi

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false

gateway:
  enabled: false

lokiCanary:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack